#!/bin/bash

# Wake target if target is suspended
sudo /usr/sbin/etherwake 00:0c:f1:77:ec:46

# Boot using novaboot
cd `dirname $0`

ln -sf ../../../jobfiles/linuxImage uImage
ln -sf ../../../tests/cyclictest/root/images/rootfs.cpio.uboot rootfs.cpio.uboot

novaboot nbscripts --exiton="NOVABOOT EXIT LINUX-CONF-PERF" --exiton-timeout=120 \
	--exiton="Kernel panic"
